import 'core-js/features/array/flat-map'

// export * from './track'
export * from './music'
export * from './elements'
export * from './note'
// export * from './sections'
export * from './durations'
export * from './validate'
export * from './data'
